spring:
  application.name: k8s-microservices-demo-customize
  cloud.kubernetes.reload.enabled: true
  cloud.kubernetes.reload.monitoring-config-maps: true
  cloud.kubernetes.reload.mode: polling
  cloud.kubernetes.reload.period: 1500

bean:
  fgcolor: black
  bgcolor: white