management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
spring:
  application:
    name: k8s-microservices-demo-customize
  cloud:
    kubernetes:
      config:
        enabled: true
      reload:
        enabled: true
        mode: event
        strategy: refresh